### ISSUE TITLE
[l10n] can we translate fedora-hubs?

### ISSUE THREAD

**Issue by Jibec** [fedoradesign/fedora-hubs#3]
Hi there, I didn't know where to ask, so I decided to do it here.

What about translation of Fedora Hubs ?
Contributors aren't all English fluent, please take into consideration to make : 
- interface translatable
- events messages translatable

I'm a little bit afraid it has be forgotten when I see this result : https://meghanrichardson.wordpress.com/?s=translation nor seeing anything in websites or design list.

I would love to have a full conversation about that, your project looks promizing, but where is the best place to discuss about that ?

I'm sorry if I missed something obvious.

**Comment by pypingou** [comment]
Was this discussed/fixed somewhere else?

**Comment by Jibec** [comment]
Le 30 mars 2017 10:43:11 UTC+02:00, Pierre-Yves Chibon <notifications@github.com> a écrit :
>Was this discussed/fixed somewhere else?

Yes, same request has been created: https://pagure.io/fedora-hubs/issue/163

I understand the project is using pagure, so it doesn't make sense to keep both tickets open.

No progress so far. I just hope they have translation in mind when choosing the tools, even if not implemented. You're probably better informed than me on this subject.
-- 
Jean-Baptiste Holcroft

**Comment by pypingou** [comment]
Ok, thanks for linking to it, this way if people find this ticket they can see where to follow  up on this :)

**Comment by Jibec** [comment]
Le 2017-03-30 11:31, Pierre-Yves Chibon a écrit :
> Ok, thanks for linking to it, this way if people find this ticket they
> can see where to follow up on this :)

Yep, I should have done it directly, thanks for pointing it out ;)
